version: '3.9'

networks:
  fullcycle-net:
    driver: bridge

services:
  node-app:
    build: 
      context: ./node-app
      dockerfile: Dockerfile
    networks:
      - fullcycle-net
    depends_on:
      - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - fullcycle-net
    ports:
      - "8080:80"
    depends_on:
      - node-app

  db:
    image: mysql
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mysql-fullcycle-db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-volume:/var/lib/mysql
    networks:
      - fullcycle-net